### ISSUE TITLE
TOC hinzufügen

### ISSUE THREAD

**Issue by Steve2955** [ZeroPointMax/sdlDoc#8]
Da die Dokumentation nun mittlerweile ziemlich umfangreich geworden ist, sollten wir eventuell einen TOC am Anfang der ``README`` hinzufügen, um schnell zu den relevanten Abschnitten springen zu können. Um sowas automatisch zu generieren gibt es bereits [diverse Programme](https://github.com/search?q=markdown+toc). 

Wenn ich mich recht erinnere, hatte ich in der Vergangenheit mal Probleme, wenn Sonderzeichen in den Hyperlinks (bzw. Überschriften) sind. Darauf sollten wir definitiv achten.

@ZeroPointMax Was hältst du davon?

**Comment by emkZero** [comment]
Gibt es da was seitens GitHub, um das nach jedem Commit neu zu erstellen? - du findest dich auf der Plattform besser zurecht als ich, aber ich suche selbst auch mal nach sowas

**Comment by Steve2955** [comment]
Von GitHub direkt nicht, aber man kann das ganze über [GitHub Actions](https://github.com/features/actions) automatisieren. Guck dir am Besten mal kurz [das hier](https://github.com/technote-space/toc-generator) an.
